#!/usr/bin/python3

classlist=[]

userclass =""

while (userclass != "Done"):
  userclass = input("What classes do you like (Type 'Done' whgen done)? ")
  if (userclass == "Done"):
    break
  else:
    classlist.append(userclass)
Print("You like the following classes:", classilist)
